<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('code' => 'AFG', 'nationality' => 'Afgana', 'name' => 'Afganistán', 'valid' => false),
            array('code' => 'ALB', 'nationality' => 'Albanés', 'name' => 'Albania', 'valid' => false),
            array('code' => 'DEU', 'nationality' => 'Alemana', 'name' => 'Alemania', 'valid' => false),
            array('code' => 'AND', 'nationality' => '', 'name' => 'Andorra', 'valid' => false),
            array('code' => 'AGO', 'nationality' => '', 'name' => 'Angola', 'valid' => false),
            array('code' => 'ATG', 'nationality' => '', 'name' => 'AntiguayBarbuda', 'valid' => false),
            array('code' => 'SAU', 'nationality' => 'Saudí', 'name' => 'ArabiaSaudita', 'valid' => false),
            array('code' => 'DZA', 'nationality' => '', 'name' => 'Argelia', 'valid' => false),
            array('code' => 'ARG', 'nationality' => 'Argentina', 'name' => 'Argentina', 'valid' => false),
            array('code' => 'ARM', 'nationality' => '', 'name' => 'Armenia', 'valid' => false),
            array('code' => 'ABW', 'nationality' => '', 'name' => 'Aruba', 'valid' => false),
            array('code' => 'AUS', 'nationality' => 'Australiana', 'name' => 'Australia', 'valid' => false),
            array('code' => 'AUT', 'nationality' => 'Austríaca', 'name' => 'Austria', 'valid' => false),
            array('code' => 'AZE', 'nationality' => '', 'name' => 'Azerbaiyán', 'valid' => false),
            array('code' => 'BHS', 'nationality' => '', 'name' => 'Bahamas', 'valid' => false),
            array('code' => 'BGD', 'nationality' => '', 'name' => 'Bangladés', 'valid' => false),
            array('code' => 'BRB', 'nationality' => '', 'name' => 'Barbados', 'valid' => false),
            array('code' => 'BHR', 'nationality' => '', 'name' => 'Baréin', 'valid' => false),
            array('code' => 'BEL', 'nationality' => 'Belga', 'name' => 'Bélgica', 'valid' => false),
            array('code' => 'BLZ', 'nationality' => '', 'name' => 'Belice', 'valid' => false),
            array('code' => 'BEN', 'nationality' => '', 'name' => 'Benín', 'valid' => false),
            array('code' => 'BLR', 'nationality' => '', 'name' => 'Bielorrusia', 'valid' => false),
            array('code' => 'MMR', 'nationality' => '', 'name' => 'Birmania', 'valid' => false),
            array('code' => 'BOL', 'nationality' => 'Boliviana', 'name' => 'Bolivia', 'valid' => false),
            array('code' => 'BIH', 'nationality' => '', 'name' => 'BosniayHerzegovina', 'valid' => false),
            array('code' => 'BWA', 'nationality' => '', 'name' => 'Botsuana', 'valid' => false),
            array('code' => 'BRA', 'nationality' => 'Brasileña', 'name' => 'Brasil', 'valid' => false),
            array('code' => 'BRN', 'nationality' => '', 'name' => 'Brunéi', 'valid' => false),
            array('code' => 'BGR', 'nationality' => '', 'name' => 'Bulgaria', 'valid' => false),
            array('code' => 'BFA', 'nationality' => '', 'name' => 'BurkinaFaso', 'valid' => false),
            array('code' => 'BDI', 'nationality' => '', 'name' => 'Burundi', 'valid' => false),
            array('code' => 'BTN', 'nationality' => '', 'name' => 'Bután', 'valid' => false),
            array('code' => 'CPV', 'nationality' => '', 'name' => 'CaboVerde', 'valid' => false),
            array('code' => 'KHM', 'nationality' => '', 'name' => 'Camboya', 'valid' => false),
            array('code' => 'CMR', 'nationality' => '', 'name' => 'Camerún', 'valid' => false),
            array('code' => 'CAN', 'nationality' => 'Canadiense', 'name' => 'Canadá', 'valid' => false),
            array('code' => 'QAT', 'nationality' => '', 'name' => 'Catar', 'valid' => false),
            array('code' => 'TCD', 'nationality' => '', 'name' => 'Chad', 'valid' => false),
            array('code' => 'CHL', 'nationality' => 'Chilena', 'name' => 'Chile', 'valid' => true),
            array('code' => 'CHN', 'nationality' => 'China', 'name' => 'China', 'valid' => false),
            array('code' => 'CYP', 'nationality' => '', 'name' => 'Chipre', 'valid' => false),
            array('code' => 'VAT', 'nationality' => '', 'name' => 'CiudaddelVaticano', 'valid' => false),
            array('code' => 'COL', 'nationality' => 'Colombiana', 'name' => 'Colombia', 'valid' => false),
            array('code' => 'COM', 'nationality' => '', 'name' => 'Comoras', 'valid' => false),
            array('code' => 'PRK', 'nationality' => 'Nor Coreana', 'name' => 'CoreadelNorte', 'valid' => false),
            array('code' => 'KOR', 'nationality' => 'Sud Coreana', 'name' => 'CoreadelSur', 'valid' => false),
            array('code' => 'CIV', 'nationality' => 'Marfileña', 'name' => 'CostadeMarfil', 'valid' => false),
            array('code' => 'CRI', 'nationality' => 'Costa Riquense', 'name' => 'CostaRica', 'valid' => false),
            array('code' => 'HRV', 'nationality' => '', 'name' => 'Croacia', 'valid' => false),
            array('code' => 'CUB', 'nationality' => 'Cubana', 'name' => 'Cuba', 'valid' => false),
            array('code' => 'DNK', 'nationality' => 'Danesa', 'name' => 'Dinamarca', 'valid' => false),
            array('code' => 'DMA', 'nationality' => '', 'name' => 'Dominica', 'valid' => false),
            array('code' => 'ECU', 'nationality' => 'Ecuatoriana', 'name' => 'Ecuador', 'valid' => false),
            array('code' => 'EGY', 'nationality' => 'Egipcia', 'name' => 'Egipto', 'valid' => false),
            array('code' => 'SLV', 'nationality' => 'Salvadoreña', 'name' => 'ElSalvador', 'valid' => false),
            array('code' => 'ARE', 'nationality' => '', 'name' => 'EmiratosÁrabesUnidos', 'valid' => false),
            array('code' => 'ERI', 'nationality' => '', 'name' => 'Eritrea', 'valid' => false),
            array('code' => 'SVK', 'nationality' => '', 'name' => 'Eslovaquia', 'valid' => false),
            array('code' => 'SVN', 'nationality' => '', 'name' => 'Eslovenia', 'valid' => false),
            array('code' => 'ESP', 'nationality' => 'Española', 'name' => 'España', 'valid' => false),
            array('code' => 'USA', 'nationality' => 'Americana', 'name' => 'EstadosUnidos', 'valid' => false),
            array('code' => 'EST', 'nationality' => '', 'name' => 'Estonia', 'valid' => false),
            array('code' => 'ETH', 'nationality' => '', 'name' => 'Etiopía', 'valid' => false),
            array('code' => 'PHL', 'nationality' => '', 'name' => 'Filipinas', 'valid' => false),
            array('code' => 'FIN', 'nationality' => 'Finlandesa', 'name' => 'Finlandia', 'valid' => false),
            array('code' => 'FJI', 'nationality' => '', 'name' => 'Fiyi', 'valid' => false),
            array('code' => 'FRA', 'nationality' => 'Francesa', 'name' => 'Francia', 'valid' => false),
            array('code' => 'GAB', 'nationality' => '', 'name' => 'Gabón', 'valid' => false),
            array('code' => 'GMB', 'nationality' => '', 'name' => 'Gambia', 'valid' => false),
            array('code' => 'GEO', 'nationality' => '', 'name' => 'Georgia', 'valid' => false),
            array('code' => 'GIB', 'nationality' => '', 'name' => 'Gibraltar', 'valid' => false),
            array('code' => 'GHA', 'nationality' => '', 'name' => 'Ghana', 'valid' => false),
            array('code' => 'GRD', 'nationality' => '', 'name' => 'Granada', 'valid' => false),
            array('code' => 'GRC', 'nationality' => '', 'name' => 'Grecia', 'valid' => false),
            array('code' => 'GRL', 'nationality' => '', 'name' => 'Groenlandia', 'valid' => false),
            array('code' => 'GTM', 'nationality' => 'Guatemalteca', 'name' => 'Guatemala', 'valid' => false),
            array('code' => 'GNQ', 'nationality' => '', 'name' => 'Guineaecuatorial', 'valid' => false),
            array('code' => 'GIN', 'nationality' => '', 'name' => 'Guinea', 'valid' => false),
            array('code' => 'GNB', 'nationality' => '', 'name' => 'Guinea-Bisáu', 'valid' => false),
            array('code' => 'GUY', 'nationality' => '', 'name' => 'Guyana', 'valid' => false),
            array('code' => 'HTI', 'nationality' => 'Haitiana', 'name' => 'Haití', 'valid' => false),
            array('code' => 'HND', 'nationality' => 'Hondureña', 'name' => 'Honduras', 'valid' => false),
            array('code' => 'HUN', 'nationality' => '', 'name' => 'Hungría', 'valid' => false),
            array('code' => 'IND', 'nationality' => 'India', 'name' => 'India', 'valid' => false),
            array('code' => 'IDN', 'nationality' => '', 'name' => 'Indonesia', 'valid' => false),
            array('code' => 'IRQ', 'nationality' => 'Iraquí', 'name' => 'Irak', 'valid' => false),
            array('code' => 'IRN', 'nationality' => 'Iraní', 'name' => 'Irán', 'valid' => false),
            array('code' => 'IRL', 'nationality' => '', 'name' => 'Irlanda', 'valid' => false),
            array('code' => 'ISL', 'nationality' => '', 'name' => 'Islandia', 'valid' => false),
            array('code' => 'COK', 'nationality' => '', 'name' => 'IslasCook', 'valid' => false),
            array('code' => 'MHL', 'nationality' => '', 'name' => 'IslasMarshall', 'valid' => false),
            array('code' => 'SLB', 'nationality' => '', 'name' => 'IslasSalomón', 'valid' => false),
            array('code' => 'ISR', 'nationality' => 'Isrraelí', 'name' => 'Israel', 'valid' => false),
            array('code' => 'ITA', 'nationality' => 'Itálica', 'name' => 'Italia', 'valid' => false),
            array('code' => 'JAM', 'nationality' => '', 'name' => 'Jamaica', 'valid' => false),
            array('code' => 'JPN', 'nationality' => 'Japonesa', 'name' => 'Japón', 'valid' => false),
            array('code' => 'JOR', 'nationality' => '', 'name' => 'Jordania', 'valid' => false),
            array('code' => 'KAZ', 'nationality' => '', 'name' => 'Kazajistán', 'valid' => false),
            array('code' => 'KEN', 'nationality' => '', 'name' => 'Kenia', 'valid' => false),
            array('code' => 'KGZ', 'nationality' => '', 'name' => 'Kirguistán', 'valid' => false),
            array('code' => 'KIR', 'nationality' => '', 'name' => 'Kiribati', 'valid' => false),
            array('code' => 'KWT', 'nationality' => '', 'name' => 'Kuwait', 'valid' => false),
            array('code' => 'LAO', 'nationality' => '', 'name' => 'Laos', 'valid' => false),
            array('code' => 'LSO', 'nationality' => '', 'name' => 'Lesoto', 'valid' => false),
            array('code' => 'LVA', 'nationality' => '', 'name' => 'Letonia', 'valid' => false),
            array('code' => 'LBN', 'nationality' => '', 'name' => 'Líbano', 'valid' => false),
            array('code' => 'LBR', 'nationality' => '', 'name' => 'Liberia', 'valid' => false),
            array('code' => 'LBY', 'nationality' => '', 'name' => 'Libia', 'valid' => false),
            array('code' => 'LIE', 'nationality' => '', 'name' => 'Liechtenstein', 'valid' => false),
            array('code' => 'LTU', 'nationality' => '', 'name' => 'Lituania', 'valid' => false),
            array('code' => 'LUX', 'nationality' => '', 'name' => 'Luxemburgo', 'valid' => false),
            array('code' => 'MDG', 'nationality' => '', 'name' => 'Madagascar', 'valid' => false),
            array('code' => 'MYS', 'nationality' => '', 'name' => 'Malasia', 'valid' => false),
            array('code' => 'MWI', 'nationality' => '', 'name' => 'Malaui', 'valid' => false),
            array('code' => 'MDV', 'nationality' => '', 'name' => 'Maldivas', 'valid' => false),
            array('code' => 'MLI', 'nationality' => '', 'name' => 'Malí', 'valid' => false),
            array('code' => 'MLT', 'nationality' => '', 'name' => 'Malta', 'valid' => false),
            array('code' => 'MAR', 'nationality' => '', 'name' => 'Marruecos', 'valid' => false),
            array('code' => 'MTQ', 'nationality' => '', 'name' => 'Martinica', 'valid' => false),
            array('code' => 'MUS', 'nationality' => '', 'name' => 'Mauricio', 'valid' => false),
            array('code' => 'MRT', 'nationality' => '', 'name' => 'Mauritania', 'valid' => false),
            array('code' => 'MEX', 'nationality' => 'Mexicana', 'name' => 'México', 'valid' => false),
            array('code' => 'FSM', 'nationality' => '', 'name' => 'Micronesia', 'valid' => false),
            array('code' => 'MDA', 'nationality' => '', 'name' => 'Moldavia', 'valid' => false),
            array('code' => 'MCO', 'nationality' => '', 'name' => 'Mónaco', 'valid' => false),
            array('code' => 'MNG', 'nationality' => '', 'name' => 'Mongolia', 'valid' => false),
            array('code' => 'MNE', 'nationality' => '', 'name' => 'Montenegro', 'valid' => false),
            array('code' => 'MOZ', 'nationality' => '', 'name' => 'Mozambique', 'valid' => false),
            array('code' => 'NAM', 'nationality' => '', 'name' => 'Namibia', 'valid' => false),
            array('code' => 'NRU', 'nationality' => '', 'name' => 'Nauru', 'valid' => false),
            array('code' => 'NPL', 'nationality' => '', 'name' => 'Nepal', 'valid' => false),
            array('code' => 'NIC', 'nationality' => 'Nicaraguense', 'name' => 'Nicaragua', 'valid' => false),
            array('code' => 'NER', 'nationality' => '', 'name' => 'Níger', 'valid' => false),
            array('code' => 'NGA', 'nationality' => '', 'name' => 'Nigeria', 'valid' => false),
            array('code' => 'NOR', 'nationality' => 'Noruega', 'name' => 'Noruega', 'valid' => false),
            array('code' => 'NZL', 'nationality' => '', 'name' => 'NuevaZelanda', 'valid' => false),
            array('code' => 'OMN', 'nationality' => '', 'name' => 'Omán', 'valid' => false),
            array('code' => 'NLD', 'nationality' => 'Holandesa', 'name' => 'PaísesBajos', 'valid' => false),
            array('code' => 'PAK', 'nationality' => '', 'name' => 'Pakistán', 'valid' => false),
            array('code' => 'PLW', 'nationality' => '', 'name' => 'Palaos', 'valid' => false),
            array('code' => 'PSE', 'nationality' => 'Palestina', 'name' => 'Palestina', 'valid' => false),
            array('code' => 'PAN', 'nationality' => 'Panameña', 'name' => 'Panamá', 'valid' => false),
            array('code' => 'PNG', 'nationality' => '', 'name' => 'PapúaNuevaGuinea', 'valid' => false),
            array('code' => 'PRY', 'nationality' => '', 'name' => 'Paraguay', 'valid' => false),
            array('code' => 'PER', 'nationality' => 'Peruana', 'name' => 'Perú', 'valid' => false),
            array('code' => 'POL', 'nationality' => '', 'name' => 'Polonia', 'valid' => false),
            array('code' => 'PRT', 'nationality' => 'Portuguesa', 'name' => 'Portugal', 'valid' => false),
            array('code' => 'PRI', 'nationality' => 'Puerto Riquense', 'name' => 'PuertoRico', 'valid' => false),
            array('code' => 'GBR', 'nationality' => 'Británica', 'name' => 'ReinoUnido', 'valid' => false),
            array('code' => 'CAF', 'nationality' => '', 'name' => 'RepúblicaCentroafricana', 'valid' => false),
            array('code' => 'CZE', 'nationality' => 'Checa', 'name' => 'RepúblicaCheca', 'valid' => false),
            array('code' => 'MKD', 'nationality' => '', 'name' => 'RepúblicadeMacedonia', 'valid' => false),
            array('code' => 'COG', 'nationality' => '', 'name' => 'RepúblicadelCongo', 'valid' => false),
            array('code' => 'COD', 'nationality' => '', 'name' => 'RepúblicaDemocráticadelCongo', 'valid' => false),
            array('code' => 'DOM', 'nationality' => 'Dominicana', 'name' => 'RepúblicaDominicana', 'valid' => false),
            array('code' => 'ZAF', 'nationality' => '', 'name' => 'Sudáfrica', 'valid' => false),
            array('code' => 'RWA', 'nationality' => '', 'name' => 'Ruanda', 'valid' => false),
            array('code' => 'ROU', 'nationality' => '', 'name' => 'Rumanía', 'valid' => false),
            array('code' => 'RUS', 'nationality' => 'Rusa', 'name' => 'Rusia', 'valid' => false),
            array('code' => 'WSM', 'nationality' => '', 'name' => 'Samoa', 'valid' => false),
            array('code' => 'KNA', 'nationality' => '', 'name' => 'SanCristóbalyNieves', 'valid' => false),
            array('code' => 'SMR', 'nationality' => '', 'name' => 'SanMarino', 'valid' => false),
            array('code' => 'VCT', 'nationality' => '', 'name' => 'SanVicenteylasGranadinas', 'valid' => false),
            array('code' => 'LCA', 'nationality' => '', 'name' => 'SantaLucía', 'valid' => false),
            array('code' => 'STP', 'nationality' => '', 'name' => 'SantoToméyPríncipe', 'valid' => false),
            array('code' => 'SEN', 'nationality' => '', 'name' => 'Senegal', 'valid' => false),
            array('code' => 'SRB', 'nationality' => '', 'name' => 'Serbia', 'valid' => false),
            array('code' => 'SYC', 'nationality' => '', 'name' => 'Seychelles', 'valid' => false),
            array('code' => 'SLE', 'nationality' => '', 'name' => 'SierraLeona', 'valid' => false),
            array('code' => 'SGP', 'nationality' => '', 'name' => 'Singapur', 'valid' => false),
            array('code' => 'SYR', 'nationality' => '', 'name' => 'Siria', 'valid' => false),
            array('code' => 'SOM', 'nationality' => '', 'name' => 'Somalia', 'valid' => false),
            array('code' => 'LKA', 'nationality' => '', 'name' => 'SriLanka', 'valid' => false),
            array('code' => 'SWZ', 'nationality' => '', 'name' => 'Suazilandia', 'valid' => false),
            array('code' => 'SSD', 'nationality' => '', 'name' => 'SudándelSur', 'valid' => false),
            array('code' => 'SDN', 'nationality' => '', 'name' => 'Sudán', 'valid' => false),
            array('code' => 'SWE', 'nationality' => '', 'name' => 'Suecia', 'valid' => false),
            array('code' => 'CHE', 'nationality' => '', 'name' => 'Suiza', 'valid' => false),
            array('code' => 'SUR', 'nationality' => '', 'name' => 'Surinam', 'valid' => false),
            array('code' => 'THA', 'nationality' => '', 'name' => 'Tailandia', 'valid' => false),
            array('code' => 'TZA', 'nationality' => '', 'name' => 'Tanzania', 'valid' => false),
            array('code' => 'TJK', 'nationality' => '', 'name' => 'Tayikistán', 'valid' => false),
            array('code' => 'TLS', 'nationality' => '', 'name' => 'TimorOriental', 'valid' => false),
            array('code' => 'TGO', 'nationality' => '', 'name' => 'Togo', 'valid' => false),
            array('code' => 'TON', 'nationality' => '', 'name' => 'Tonga', 'valid' => false),
            array('code' => 'TTO', 'nationality' => '', 'name' => 'TrinidadyTobago', 'valid' => false),
            array('code' => 'TUN', 'nationality' => '', 'name' => 'Túnez', 'valid' => false),
            array('code' => 'TKM', 'nationality' => '', 'name' => 'Turkmenistán', 'valid' => false),
            array('code' => 'TUR', 'nationality' => '', 'name' => 'Turquía', 'valid' => false),
            array('code' => 'TUV', 'nationality' => '', 'name' => 'Tuvalu', 'valid' => false),
            array('code' => 'UKR', 'nationality' => '', 'name' => 'Ucrania', 'valid' => false),
            array('code' => 'UGA', 'nationality' => '', 'name' => 'Uganda', 'valid' => false),
            array('code' => 'URY', 'nationality' => 'Uruguaya', 'name' => 'Uruguay', 'valid' => false),
            array('code' => 'UZB', 'nationality' => '', 'name' => 'Uzbekistán', 'valid' => false),
            array('code' => 'VUT', 'nationality' => '', 'name' => 'Vanuatu', 'valid' => false),
            array('code' => 'VEN', 'nationality' => 'Venezolana', 'name' => 'Venezuela', 'valid' => false),
            array('code' => 'VNM', 'nationality' => '', 'name' => 'Vietnam', 'valid' => false),
            array('code' => 'YEM', 'nationality' => '', 'name' => 'Yemen', 'valid' => false),
            array('code' => 'DJI', 'nationality' => '', 'name' => 'Yibuti', 'valid' => false),
            array('code' => 'ZMB', 'nationality' => '', 'name' => 'Zambia', 'valid' => false),
            array('code' => 'ZWE', 'nationality' => '', 'name' => 'Zimbabue', 'valid' => false)
        );
        DB::table('countries')->insert($countries);
    }
}
