<?php

use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $regions = array(

            array('name' => 'Arica y Parinacota', 'country_id' => 39),
            array('name' => 'Tarapacá', 'country_id' => 39),
            array('name' => 'Antofagasta', 'country_id' => 39),
            array('name' => 'Atacama', 'country_id' => 39),
            array('name' => 'Coquimbo', 'country_id' => 39),
            array('name' => 'Valparaiso', 'country_id' => 39),
            array('name' => 'Metropolitana de Santiago', 'country_id' => 39),
            array('name' => 'Libertador General Bernardo O\'Higgins', 'country_id' => 39),
            array('name' => 'Maule', 'country_id' => 39),
            array('name' => 'Biobío', 'country_id' => 39),
            array('name' => 'La Araucanía', 'country_id' => 39),
            array('name' => 'Los Ríos', 'country_id' => 39),
            array('name' => 'Los Lagos', 'country_id' => 39),
            array('name' => 'Aisén del General Carlos Ibáñez del Campo', 'country_id' => 39),
            array('name' => 'Magallanes y de la Antártica Chilena', 'country_id' => 39),
            array('name' => 'Vargas', 'country_id' => 196),
            array('name' => 'Trujillo', 'country_id' => 196),
            array('name' => 'Táchira', 'country_id' => 196),
            array('name' => 'Sucre', 'country_id' => 196),
            array('name' => 'Portuguesa', 'country_id' => 196),
            array('name' => 'Nueva Esparta', 'country_id' => 196),
            array('name' => 'Monagas', 'country_id' => 196),
            array('name' => 'Miranda', 'country_id' => 196),
            array('name' => 'Mérida', 'country_id' => 196),
            array('name' => 'Lara', 'country_id' => 196),
            array('name' => 'Guárico', 'country_id' => 196),
            array('name' => 'Falcón', 'country_id' => 196),
            array('name' => 'Delta Amacuro', 'country_id' => 196),
            array('name' => 'Cojedes', 'country_id' => 196),
            array('name' => 'Carabobo', 'country_id' => 196),
            array('name' => 'Bolívar', 'country_id' => 196),
            array('name' => 'Barinas', 'country_id' => 196),
            array('name' => 'Aragua', 'country_id' => 196),
            array('name' => 'Apure', 'country_id' => 196),
            array('name' => 'Anzoátegui', 'country_id' => 196),
            array('name' => 'Amazonas', 'country_id' => 196),
            array('name' => 'Yaracuy', 'country_id' => 196),
            array('name' => 'Zulia', 'country_id' => 196),
            array('name' => 'Distrito Capital', 'country_id' => 196),
            array('name' => 'Amazonas', 'country_id' => 43),
            array('name' => 'Antioquia', 'country_id' => 43),
            array('name' => 'Arauca', 'country_id' => 43),
            array('name' => 'Atlántico', 'country_id' => 43),
            array('name' => 'Bolívar', 'country_id' => 43),
            array('name' => 'Boyacá', 'country_id' => 43),
            array('name' => 'Caldas', 'country_id' => 43),
            array('name' => 'Caquetá', 'country_id' => 43),
            array('name' => 'Casanare', 'country_id' => 43),
            array('name' => 'Cauca', 'country_id' => 43),
            array('name' => 'Cesar', 'country_id' => 43),
            array('name' => 'Chocó', 'country_id' => 43),
            array('name' => 'Cundinamarca', 'country_id' => 43),
            array('name' => 'Córdoba', 'country_id' => 43),
            array('name' => 'Guainía', 'country_id' => 43),
            array('name' => 'Guaviare', 'country_id' => 43),
            array('name' => 'Huila', 'country_id' => 43),
            array('name' => 'La Guajira', 'country_id' => 43),
            array('name' => 'Magdalena', 'country_id' => 43),
            array('name' => 'Meta', 'country_id' => 43),
            array('name' => 'Nariño', 'country_id' => 43),
            array('name' => 'Norte de Santander', 'country_id' => 43),
            array('name' => 'Putumayo', 'country_id' => 43),
            array('name' => 'Quindío', 'country_id' => 43),
            array('name' => 'Risaralda', 'country_id' => 43),
            array('name' => 'San Andrés y Providencia', 'country_id' => 43),
            array('name' => 'Santander', 'country_id' => 43),
            array('name' => 'Sucre', 'country_id' => 43),
            array('name' => 'Tolima', 'country_id' => 43),
            array('name' => 'Valle del Cauca', 'country_id' => 43),
            array('name' => 'Vaupés', 'country_id' => 43),
            array('name' => 'Vichada', 'country_id' => 43),
            array('name' => 'Aguascalientes', 'country_id' => 122),
            array('name' => 'Baja California', 'country_id' => 122),
            array('name' => 'Baja California Sur', 'country_id' => 122),
            array('name' => 'Campeche', 'country_id' => 122),
            array('name' => 'Chiapas', 'country_id' => 122),
            array('name' => 'Chihuahua', 'country_id' => 122),
            array('name' => 'Coahuila', 'country_id' => 122),
            array('name' => 'Colima', 'country_id' => 122),
            array('name' => 'Distrito Federal', 'country_id' => 122),
            array('name' => 'Durango', 'country_id' => 122),
            array('name' => 'Estado de Mexico', 'country_id' => 122),
            array('name' => 'Guanajuato', 'country_id' => 122),
            array('name' => 'Guerrero', 'country_id' => 122),
            array('name' => 'Hidalgo', 'country_id' => 122),
            array('name' => 'Jalisco', 'country_id' => 122),
            array('name' => 'Michoacan', 'country_id' => 122),
            array('name' => 'Morelos', 'country_id' => 122),
            array('name' => 'Nayarit', 'country_id' => 122),
            array('name' => 'Nuevo Leon', 'country_id' => 122),
            array('name' => 'Oaxaca', 'country_id' => 122),
            array('name' => 'Puebla', 'country_id' => 122),
            array('name' => 'Queretaro', 'country_id' => 122),
            array('name' => 'Quintana Roo', 'country_id' => 122),
            array('name' => 'San Luis Potosi', 'country_id' => 122),
            array('name' => 'Sinaloa', 'country_id' => 122),
            array('name' => 'Sonora', 'country_id' => 122),
            array('name' => 'Tabasco', 'country_id' => 122),
            array('name' => 'Tamaulipas', 'country_id' => 122),
            array('name' => 'Tlaxcala', 'country_id' => 122),
            array('name' => 'Veracruz', 'country_id' => 122),
            array('name' => 'Yucatan', 'country_id' => 122),
            array('name' => 'Zacatecas', 'country_id' => 122),
            array('name' => 'Salta', 'country_id' => 9),
            array('name' => 'Buenos Aires', 'country_id' => 9),
            array('name' => 'San Luis', 'country_id' => 9),
            array('name' => 'Entre Ríos', 'country_id' => 9),
            array('name' => 'La Rioja', 'country_id' => 9),
            array('name' => 'Santiago del Estero', 'country_id' => 9),
            array('name' => 'Chaco', 'country_id' => 9),
            array('name' => 'San Juan', 'country_id' => 9),
            array('name' => 'Catamarca', 'country_id' => 9),
            array('name' => 'La Pampa', 'country_id' => 9),
            array('name' => 'Mendoza', 'country_id' => 9),
            array('name' => 'Misiones', 'country_id' => 9),
            array('name' => 'Formosa', 'country_id' => 9),
            array('name' => 'Neuquén', 'country_id' => 9),
            array('name' => 'Río Negro', 'country_id' => 9),
            array('name' => 'Santa Fe', 'country_id' => 9),
            array('name' => 'Tucumán', 'country_id' => 9),
            array('name' => 'Chubut', 'country_id' => 9),
            array('name' => 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'country_id' => 9),
            array('name' => 'Corrientes', 'country_id' => 9),
            array('name' => 'Córdoba', 'country_id' => 9),
            array('name' => 'Jujuy', 'country_id' => 9),
            array('name' => 'Santa Cruz', 'country_id' => 9),
            array('name' => 'Capital Federal', 'country_id' => 9)
        );
        DB::table('regions')->insert($regions);
        }
}
